### ISSUE TITLE
Deprecation warning when trying to run pytest

### ISSUE THREAD

**Issue by pioneerHitesh** [microsoft/torchgeo#1687]
### Description

Running ``pytest --cov=torchgeo --cov-report=xml --durations=10 `` results in the following error-
```
ERROR: while parsing the following warning configuration:

  ignore:The .*dataloader.* does not have many workers which may be a bottleneck:lightning.fabric.utilities.warnings.PossibleUserWarning:lightning

This error occurred:

Traceback (most recent call last):
  File "/mnt/data/test/torchgeo/env/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1761, in parse_warning_filter
    category: Type[Warning] = _resolve_warning_category(category_)
  File "/mnt/data/test/torchgeo/env/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1799, in _resolve_warning_category
    m = __import__(module, None, None, [klass])
  File "/mnt/data/test/torchgeo/env/lib/python3.10/site-packages/lightning/__init__.py", line 19, in <module>
    from lightning.pytorch.callbacks import Callback  # noqa: E402
  File "/mnt/data/test/torchgeo/env/lib/python3.10/site-packages/lightning/pytorch/__init__.py", line 27, in <module>
    from lightning.pytorch.callbacks import Callback  # noqa: E402
  File "/mnt/data/test/torchgeo/env/lib/python3.10/site-packages/lightning/pytorch/callbacks/__init__.py", line 14, in <module>
    from lightning.pytorch.callbacks.batch_size_finder import BatchSizeFinder
  File "/mnt/data/test/torchgeo/env/lib/python3.10/site-packages/lightning/pytorch/callbacks/batch_size_finder.py", line 24, in <module>
    from lightning.pytorch.callbacks.callback import Callback
  File "/mnt/data/test/torchgeo/env/lib/python3.10/site-packages/lightning/pytorch/callbacks/callback.py", line 22, in <module>
    from lightning.pytorch.utilities.types import STEP_OUTPUT
  File "/mnt/data/test/torchgeo/env/lib/python3.10/site-packages/lightning/pytorch/utilities/types.py", line 40, in <module>
    from torchmetrics import Metric
  File "/mnt/data/test/torchgeo/env/lib/python3.10/site-packages/torchmetrics/__init__.py", line 14, in <module>
    from torchmetrics import functional  # noqa: E402
  File "/mnt/data/test/torchgeo/env/lib/python3.10/site-packages/torchmetrics/functional/__init__.py", line 14, in <module>
    from torchmetrics.functional.audio._deprecated import _permutation_invariant_training as permutation_invariant_training
  File "/mnt/data/test/torchgeo/env/lib/python3.10/site-packages/torchmetrics/functional/audio/__init__.py", line 14, in <module>
    from torchmetrics.functional.audio.pit import permutation_invariant_training, pit_permutate
  File "/mnt/data/test/torchgeo/env/lib/python3.10/site-packages/torchmetrics/functional/audio/pit.py", line 22, in <module>
    from torchmetrics.utilities import rank_zero_warn
  File "/mnt/data/test/torchgeo/env/lib/python3.10/site-packages/torchmetrics/utilities/__init__.py", line 14, in <module>
    from torchmetrics.utilities.checks import check_forward_full_state_property
  File "/mnt/data/test/torchgeo/env/lib/python3.10/site-packages/torchmetrics/utilities/checks.py", line 25, in <module>
    from torchmetrics.metric import Metric
  File "/mnt/data/test/torchgeo/env/lib/python3.10/site-packages/torchmetrics/metric.py", line 30, in <module>
    from torchmetrics.utilities.data import (
  File "/mnt/data/test/torchgeo/env/lib/python3.10/site-packages/torchmetrics/utilities/data.py", line 22, in <module>
    from torchmetrics.utilities.imports import _TORCH_GREATER_EQUAL_1_12, _XLA_AVAILABLE
  File "/mnt/data/test/torchgeo/env/lib/python3.10/site-packages/torchmetrics/utilities/imports.py", line 18, in <module>
    from distutils.version import LooseVersion
  File "/usr/lib/python3.10/distutils/__init__.py", line 19, in <module>
    warnings.warn(_DEPRECATION_MESSAGE,
DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
```

### Steps to reproduce

``pytest --cov=torchgeo --cov-report=xml --durations=10``

### Version

latest github repo.

**Comment by adamjstewart** [comment]
This warning was fixed in https://github.com/Lightning-AI/torchmetrics/pull/2137 but hasn't been released yet, I'll add an ignore to `pyproject.toml`.

FWIW, if you encounter these kinds of issues, you can uncomment [this line](https://github.com/microsoft/torchgeo/blob/v0.5.0/pyproject.toml#L201) to ignore them.

**Comment by pioneerHitesh** [comment]
This does not fix the issue which is leading to to ubuntu tests being stalled.

**Comment by pioneerHitesh** [comment]
The issue is fixed by #1688
