### ISSUE TITLE
Auto download of ETCI2021 is broken

### ISSUE THREAD

**Issue by calebrob6** [microsoft/torchgeo#229]
It seems the download results in a corrupt zip file.

Steps to reproduce:
```
ETCI2021("data/", split="train", download=True, checksum=True)
```

**Comment by isaaccorley** [comment]
This is a known bug caused by torchvision's download_url being broken for google drive files. If I remember correctly the files aren't downloaded at all, it just creates empty files. This happens for all of our datasets which are hosted on google drive.

**Comment by calebrob6** [comment]
Yeah I remember that issue. This time it downloads, but the download is corrupt. I manually downloaded a copy of the dataset so it isn't _super_ urgent to look into this.

**Comment by calebrob6** [comment]
I emailed the hosts of ETCI2021 and they said the whole dataset (included held out test labels) will be hosted on MLHub. Radiant Earth folks estimate that this will happen in early 2022.

**Comment by calebrob6** [comment]
Just checked and this is fixed with torchvision 0.11

**Comment by alirezaomidi** [comment]
It seems the problem is back again. Check this colab notebook: https://colab.research.google.com/drive/1xbf3KlvFXQVljXZeZ73ufFsu-mPvo14W?usp=sharing

**Comment by adamjstewart** [comment]
Just tried this with torchvision 0.13.0 and it works fine. Anyone experiencing issues with downloads should try to upgrade to a newer torchvision release.
