### ISSUE TITLE
Resnet50 pretrained model documentation

### ISSUE THREAD

**Issue by nilsleh** [microsoft/torchgeo#799]
### Issue

- The documentation suggests that the `sensor` flag can take on several sources, but one has to go into the source code to find out which values are possible
- The documentation states that the `bands` flag can accept 'all' or 'rgb', however, currently only 'all' is supported and specifying 'rgb' throws an error
- Add documentation that Sentinel2 imagery is pretrained on 10 channels and which of the overall available 13 channels they are so that downstream tasks can be configured accordingly

I can open an PR if there are suggestions to the above issues and change the documentation accordingly.

### Fix

Be more clear about which values are currently supported and an explanation about how the pretrained weights came about.

**Comment by adamjstewart** [comment]
This relates to both #762 and #693. To fix the first 2 issues, moving to a multi-weight API like torchvision is using now should solve that problem. For the 3rd issue, we should just train on a different dataset that has all bands in order instead of our current training approach.

**Comment by FlorisCalkoen** [comment]
Hi, so I would like to use the S2 pretrained model, but I'm not sure how to implement it as a `pl.LightningModule`. Any chance still have a snippet? 

So I'm trying to do a MultiLabelClassification, something like this, but then with resnet50 backbone trained on So2Sat

```python


task = MultiLabelClassificationTask(
    classification_model="resnet18",  # "resnet50"?  or resnet50(sensor="sentinel2", bands="all", pretrained=True)?
    pretrained=True,
    learning_rate=0.1,
    learning_rate_schedule_patience=5,
    in_channels=4,
    weights="imagenet",   # "sentinel2" ?
    num_classes=5,
    loss="bce",
)
...

trainer.fit(model=task, datamodule=datamodule)

```
